set_property IOSTANDARD LVCMOS33 [get_ports {clock}]
set_property PACKAGE_PIN P17 [get_ports {clock}]


set_property IOSTANDARD LVCMOS33 [get_ports {rst}]
set_property PACKAGE_PIN R15 [get_ports {rst}]

set_property IOSTANDARD LVCMOS33 [get_ports {confirm_button}]
set_property PACKAGE_PIN R11 [get_ports {confirm_button}]


set_property IOSTANDARD LVCMOS33 [get_ports {switches[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[8]}]

set_property IOSTANDARD LVCMOS33 [get_ports {switches[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[0]}]


set_property PACKAGE_PIN P5 [get_ports {switches[15]}]
set_property PACKAGE_PIN P4 [get_ports {switches[14]}]
set_property PACKAGE_PIN P3 [get_ports {switches[13]}]
set_property PACKAGE_PIN P2 [get_ports {switches[12]}]
set_property PACKAGE_PIN R2 [get_ports {switches[11]}]
set_property PACKAGE_PIN M4 [get_ports {switches[10]}]
set_property PACKAGE_PIN N4 [get_ports {switches[9]}]
set_property PACKAGE_PIN R1 [get_ports {switches[8]}]

set_property PACKAGE_PIN U3 [get_ports {switches[7]}]
set_property PACKAGE_PIN U2 [get_ports {switches[6]}]
set_property PACKAGE_PIN V2 [get_ports {switches[5]}]
set_property PACKAGE_PIN V5 [get_ports {switches[4]}]
set_property PACKAGE_PIN V4 [get_ports {switches[3]}]
set_property PACKAGE_PIN R3 [get_ports {switches[2]}]
set_property PACKAGE_PIN T3 [get_ports {switches[1]}]
set_property PACKAGE_PIN T5 [get_ports {switches[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {ledss[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[8]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ledss[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ledss[0]}]


set_property PACKAGE_PIN F6 [get_ports {ledss[15]}]
set_property PACKAGE_PIN G4 [get_ports {ledss[14]}]
set_property PACKAGE_PIN G3 [get_ports {ledss[13]}]
set_property PACKAGE_PIN J4 [get_ports {ledss[12]}]
set_property PACKAGE_PIN H4 [get_ports {ledss[11]}]
set_property PACKAGE_PIN J3 [get_ports {ledss[10]}]
set_property PACKAGE_PIN J2 [get_ports {ledss[9]}]
set_property PACKAGE_PIN K2 [get_ports {ledss[8]}]

set_property PACKAGE_PIN K1 [get_ports {ledss[7]}]
set_property PACKAGE_PIN H6 [get_ports {ledss[6]}]
set_property PACKAGE_PIN H5 [get_ports {ledss[5]}]
set_property PACKAGE_PIN J5 [get_ports {ledss[4]}]
set_property PACKAGE_PIN K6 [get_ports {ledss[3]}]
set_property PACKAGE_PIN L1 [get_ports {ledss[2]}]
set_property PACKAGE_PIN M1 [get_ports {ledss[1]}]
set_property PACKAGE_PIN K3 [get_ports {ledss[0]}]

