# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/Documents/project/CPU/CPU/CPU.srcs/sources/prgrom/prgrom.xci
# IP: The module: 'prgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/project/CPU/CPU/CPU.srcs/sources/prgrom/prgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgrom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: z:/Documents/project/CPU/CPU/CPU.srcs/sources/prgrom/prgrom.xci
# IP: The module: 'prgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/project/CPU/CPU/CPU.srcs/sources/prgrom/prgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
