# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/29266/Desktop/Homework/Computer Organization/CPU/RAM/RAM.xci
# IP: The module: 'RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/29266/Desktop/Homework/Computer Organization/CPU/RAM/RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/29266/Desktop/Homework/Computer Organization/CPU/RAM/RAM.xci
# IP: The module: 'RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/29266/Desktop/Homework/Computer Organization/CPU/RAM/RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
